# Generated by Django 5.2.1 on 2025-06-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificaciontramites',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='detalletramite',
            name='clasificacion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='detalletramite',
            name='documento_obtenido',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='detalletramite',
            name='medios_presentacion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='detalletramite',
            name='nombre_por_normatividad',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='detalletramite',
            name='unidad_administrativa',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='TramiteArchivoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='tramites_anexos/')),
                ('orden', models.IntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_anexos', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_archivo_anexo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('unidad_valor', models.CharField(max_length=50)),
                ('fundamento_juridico', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_costo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteFundamentoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ley', models.CharField(max_length=500)),
                ('articulos', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentos_juridicos', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_fundamento_juridico',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteInformacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_adicional', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_informacion_adicional',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_modalidad', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_modalidad',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteOficinaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('numero_exterior', models.CharField(max_length=20)),
                ('numero_interior', models.CharField(blank=True, max_length=20)),
                ('colonia', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('horario_atencion', models.TextField()),
                ('telefonos', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=50)),
                ('email_responsable', models.EmailField(max_length=254)),
                ('nombre_responsable', models.CharField(max_length=255)),
                ('puesto_responsable', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas_atencion', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_oficina_atencion',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteOpcionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('observacion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_pago', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_opcion_pago',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('tramite_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_relacionados', to='tramites.tramite')),
                ('tramite_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionado_con', to='tramites.tramite')),
            ],
            options={
                'db_table': 'tramite_relacionado',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramiteRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_requisito', models.CharField(choices=[('ACCION', 'Acción'), ('DOCUMENTO', 'Documento')], max_length=20)),
                ('original', models.IntegerField(default=0)),
                ('copia', models.CharField(default='0', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='tramites.tramitemodalidad')),
            ],
            options={
                'db_table': 'tramite_requisito',
                'ordering': ['orden'],
            },
        ),
    ]
