# Generated by Django 5.2.1 on 2025-06-05 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0008_alter_detalletramite_nombre_por_normatividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtestaCiudadana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_PROCESO', 'En Proceso'), ('APROBADA', 'Aprobada'), ('NEGADA', 'Negada')], default='RECIBIDA', max_length=20)),
                ('area', models.CharField(max_length=300)),
                ('responsable', models.CharField(max_length=300)),
                ('nombre_tramite', models.TextField()),
                ('objeto_protesta', models.TextField()),
                ('clv_motivo', models.IntegerField(choices=[(1, 'NIEGUE LA GESTION DE SU TRAMITE O SERVICIO SIN CAUSA JUSTIFICADA'), (2, 'EXIJA REQUISITOS O DOCUMENTOS ADICIONALES'), (3, 'EXIJA UN FORMATO ADICIONAL O DIFERENTE AL SEÑALADO EN EL REGISTRO DE TRAMITES Y SERVICIOS'), (4, 'PRETENDA COBRAR CUOTAS ADICIONALES O DISTINTAS A LAS PUBLICADAS'), (5, 'NO RESPETE LA VIGENCIA DEL TRAMITE O SERVICIO'), (6, 'SE REALICEN INSPECCIONES O VERIFICACIONES QUE NO CORRESPONDAN O QUE EXCEDAN LO PERMITIDO O PREVISTO'), (7, 'NO SE RESPETEN LOS CRITERIOS PARA RESOLVER SU SOLICITUD'), (8, 'SE PROPORCIONEN DATOS DE CONTACTO ERRONEOS DEL RESPONSABLE DEL TRAITE O SERVICIO'), (9, 'OTRO')])),
                ('tipo_tramite', models.CharField(choices=[('C', 'Ciudadano'), ('E', 'Empresarial')], default='C', max_length=1)),
                ('folio_referencia', models.CharField(max_length=200)),
                ('es_presencial', models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], default=1)),
                ('lugar_administrativa', models.CharField(blank=True, max_length=300)),
                ('liga_internet', models.URLField(blank=True)),
                ('fecha_tramite', models.DateField()),
                ('hora_tramite', models.TimeField()),
                ('rfc', models.CharField(max_length=14)),
                ('calificacion_afectacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('costo_afectacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_letra_afectacion', models.CharField(max_length=480)),
                ('empleos_afectacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=200)),
                ('num_ext', models.CharField(max_length=9)),
                ('num_int', models.CharField(blank=True, max_length=9)),
                ('colonia', models.CharField(max_length=299)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('referencias_domicilio', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('movil', models.CharField(blank=True, max_length=10)),
                ('descripcion_protesta', models.TextField()),
                ('servidor_publico', models.CharField(max_length=300)),
                ('archivo_identificacion', models.FileField(blank=True, upload_to='protestas/identificacion/')),
                ('archivo_comprobante_dom', models.FileField(blank=True, upload_to='protestas/comprobantes/')),
                ('evidencia', models.FileField(blank=True, upload_to='protestas/evidencias/')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protestas', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Protesta Ciudadana',
                'verbose_name_plural': 'Protestas Ciudadanas',
                'db_table': 'protesta_ciudadana',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
