# Generated by Django 5.2.1 on 2025-06-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0009_protestaciudadana'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='grupo_usuario',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMINISTRADOR', 'Administrador'), ('GESTOR_PROTESTAS', 'Gestor de Protestas'), ('GESTOR_TRAMITES', 'Gestor de Trámites')], default='GESTOR_TRAMITES', max_length=20),
        ),
    ]
