# Generated by Django 5.2.1 on 2025-05-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionTramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(help_text='Ruta dentro de static/, por ejemplo: imagenes/salchichasiconoscontraloriamunicipal.png', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.clasificaciontramites')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_administrativa', models.CharField(max_length=255)),
                ('descripcion_servicio', models.TextField()),
                ('nombre_por_normatividad', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=100)),
                ('medios_presentacion', models.CharField(max_length=255)),
                ('documento_obtenido', models.CharField(max_length=255)),
                ('criterios_resolucion', models.TextField()),
                ('requiere_inspeccion', models.BooleanField(default=False)),
                ('objetivo_inspeccion', models.TextField()),
                ('archivo_anexo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite')),
            ],
        ),
    ]
