# Generated by Django 5.2.1 on 2025-05-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_alter_clasificaciontramites_imagen_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClasificacionTramites',
            new_name='clasificacion_tramites',
        ),
    ]
