# Generated by Django 5.2.1 on 2025-05-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_rename_clasificaciontramites_clasificacion_tramites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clasificacion_tramites',
            new_name='ClasificacionTramites',
        ),
    ]
