# Generated by Django 5.2.1 on 2025-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_alter_clasificaciontramites_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletramite',
            name='nombre_por_normatividad',
            field=models.TextField(),
        ),
    ]
